# Generated by Django 5.0.7 on 2024-09-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_review_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
