# Generated by Django 5.0.7 on 2024-09-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_genre1_alter_movie_genre2'),
        ('users', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_movie_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'profile')},
        ),
    ]
