# Generated by Django 5.0.7 on 2024-08-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0002_room'),
        ('movies', '0003_movie_genre1_movie_genre2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.CharField(choices=[('13:00', '13:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=5)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemas.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinemas.room')),
            ],
        ),
    ]
