# Generated by Django 5.0.7 on 2024-08-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_room'),
        ('sessoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('room', 'date', 'hour')},
        ),
    ]
