# Generated by Django 5.0.7 on 2024-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Documentary', 'Documentary'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-fi'), ('Superhero', 'Superhero'), ('Psychological Horror', 'Psychological Horror')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plot', models.CharField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('director', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('poster', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
