# Generated by Django 5.0.7 on 2024-08-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessoes', '0001_initial'),
        ('users', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.PositiveIntegerField()),
                ('ticketType', models.CharField(choices=[('MEIA', 'Meia Entrada'), ('IDOSO', 'Idoso'), ('NORMAL', 'Normal')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_reserved', models.BooleanField(default=False)),
                ('purchasedAt', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessoes.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
