# Generated by Django 5.0.7 on 2024-08-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('DONE', 'Concluído'), ('PENDING', 'Pendente'), ('CANCELLED', 'Cancelado'), ('FREE', 'Livre')], default='FREE', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payMethod', models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PAYPAL', 'PayPal'), ('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=10)),
                ('transactionId', models.CharField(max_length=100, unique=True)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
