# Generated by Django 5.0.7 on 2024-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
