# Generated by Django 5.0.7 on 2024-08-18 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0001_initial'),
        ('tickets', '0005_ticket_history'),
        ('users', '0004_profile_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCancelled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ticket_id', models.PositiveIntegerField()),
                ('seatNumber', models.PositiveIntegerField()),
                ('ticketType', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchasedAt', models.DateTimeField()),
                ('cancelledAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessoes.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
