# Generated by Django 5.0.7 on 2024-08-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketcancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payMethod',
            field=models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário')], max_length=20),
        ),
    ]
